---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: project
  namespace: baknine
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: baknine
  name: baknine-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: baknine-rolebinding
  namespace: baknine
subjects:
  - kind: ServiceAccount
    name: project
    namespace: baknine
roleRef:
  kind: Role
  name: baknine-role
  apiGroup: rbac.authorization.k8s.io
